name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      # Install Golang for the specific OS and version (optional)
      - name: Set up Go environment
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v3
        with:
          command: staticcheck --version
